package com.maverick.flightadminservice.airport.entities;

import jakarta.persistence.*;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Objects;

@Entity
@Table(name = "airports")
public class Airport {

    /**
     * Surrogate primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Three-letter IATA airport code (for example, JFK).
     */
    @Column(name = "iata_code", nullable = false, unique = true, length = 3)
    private String iataCode;

    /**
     * Four-letter ICAO airport code (for example, KJFK).
     */
    @Column(name = "icao_code", nullable = false, unique = true, length = 4)
    private String icaoCode;

    /**
     * Official airport name.
     */
    @Column(nullable = false, length = 150)
    private String name;

    /**
     * City where the airport is located.
     */
    @Column(nullable = false, length = 100)
    private String city;

    /**
     * ISO 3166-1 alpha-2 country code for the airport location.
     */
    @Column(name = "country_code", nullable = false, length = 2)
    private String countryCode;

    /**
     * IANA time zone identifier used by the airport (for example, America/New_York).
     */
    @Column(nullable = false, length = 100)
    private String timezone;

    /**
     * Indicates whether the airport is currently active in the system.
     */
    @Column(nullable = false)
    private boolean active;

    /**
     * UTC timestamp when the record was first created.
     */
    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    /**
     * UTC timestamp when the record was last updated.
     */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    protected Airport() {
    }

    public Airport(
            String iataCode,
            String icaoCode,
            String name,
            String city,
            String countryCode,
            String timezone
    ) {
        this.iataCode = iataCode;
        this.icaoCode = icaoCode;
        this.name = name;
        this.city = city;
        this.countryCode = countryCode;
        this.timezone = timezone;
        this.active = true;
    }

    @PrePersist
    void onCreate() {
        OffsetDateTime now = OffsetDateTime.now(ZoneOffset.UTC);
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        this.updatedAt = OffsetDateTime.now(ZoneOffset.UTC);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Airport other)) {
            return false;
        }

        if (id != null && other.id != null) {
            return id.equals(other.id);
        }

        return Objects.equals(iataCode, other.iataCode)
                && Objects.equals(icaoCode, other.icaoCode)
                && Objects.equals(countryCode, other.countryCode);
    }

    @Override
    public int hashCode() {
        if (id != null) {
            return id.hashCode();
        }
        return Objects.hash(iataCode, icaoCode, countryCode);
    }

    public Long getId() {
        return id;
    }

    public String getIataCode() {
        return iataCode;
    }

    public String getIcaoCode() {
        return icaoCode;
    }

    public String getName() {
        return name;
    }

    public String getCity() {
        return city;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public String getTimezone() {
        return timezone;
    }

    public boolean isActive() {
        return active;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }
}
