package com.maverick.flightadminservice.flight.entities;

import com.maverick.flightadminservice.airport.entities.Airport;
import com.maverick.flightadminservice.flight.enums.FlightStatus;
import jakarta.persistence.*;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;

@Entity
@Table(name = "flights")
public class Flight {

    /**
     * Surrogate primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Airline flight designator used to identify this flight (for example, AA100).
     */
    @Column(name = "flight_number", nullable = false, length = 10)
    private String flightNumber;

    /**
     * Airport where the flight departs from.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "origin_airport_id", nullable = false)
    private Airport originAirport;

    /**
     * Airport where the flight arrives.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "destination_airport_id", nullable = false)
    private Airport destinationAirport;

    /**
     * Scheduled departure date-time in UTC offset form.
     */
    @Column(name = "scheduled_departure", nullable = false)
    private OffsetDateTime scheduledDeparture;

    /**
     * Scheduled arrival date-time in UTC offset form.
     */
    @Column(name = "scheduled_arrival", nullable = false)
    private OffsetDateTime scheduledArrival;

    /**
     * Current lifecycle state of the flight (for example, SCHEDULED, CANCELLED).
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private FlightStatus status;

    /**
     * UTC timestamp when the record was first created.
     */
    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    /**
     * UTC timestamp when the record was last updated.
     */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    public Flight() {
    }

    public Flight(
            String flightNumber,
            Airport originAirport,
            Airport destinationAirport,
            OffsetDateTime scheduledDeparture,
            OffsetDateTime scheduledArrival
    ) {
        this.flightNumber = flightNumber;
        this.originAirport = originAirport;
        this.destinationAirport = destinationAirport;
        this.scheduledDeparture = scheduledDeparture;
        this.scheduledArrival = scheduledArrival;
        this.status = FlightStatus.SCHEDULED;
    }

    @PrePersist
    void onCreate() {
        OffsetDateTime now = OffsetDateTime.now(ZoneOffset.UTC);
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        this.updatedAt = OffsetDateTime.now(ZoneOffset.UTC);
    }

    public Long getId() {
        return id;
    }

    public String getFlightNumber() {
        return flightNumber;
    }

    public Airport getOriginAirport() {
        return originAirport;
    }

    public Airport getDestinationAirport() {
        return destinationAirport;
    }

    public OffsetDateTime getScheduledDeparture() {
        return scheduledDeparture;
    }

    public OffsetDateTime getScheduledArrival() {
        return scheduledArrival;
    }

    public FlightStatus getStatus() {
        return status;
    }
}
